endoflife-date/release-data

README.md

Shouldn't a newly tracked product be added automatically?

Add CakePHP to "Currently Updated" list

---

.github/workflows/trigger-deploy.yml

This triggers a new build, but only on commits to the main branch.
See https://github.com/endoflife-date/endoflife.date/pull/2081 for why

[ci] Trigger website deploy on new release-data build

---

.github/workflows/update.yml
update.rb

Add `--depth=1` to the git fetch command to minimize the git repositories size.
A test showed that this reduced the cache size from 7507 MB to 962 MB.

Minimize git cache size

---

src/sles.py

I've added a scraper for SUSE Linux Enterprise Server that parses data from https://www.suse.com/lifecycle and produces a JSON with information about both major and minor SLES releases.
@marcwrobel, @captn3m0, this generates data more detailed than what is currently available (https://github.com/endoflife-date/endoflife.date/blob/master/products/sles.md) - instead of reporting SLES 10, 11, 12, 15, it reports also minor versions/service packs like SLES 15 SP 3. Please confirm that it is ok for you.
I'm going to create a separate PR in the main repository modifying the .md file.

[SLES] Add SLES version scraper

---

src/ibm-aix.py

Added an automated release date scraper for IBM AIX operating system.
The data is taken from https://www.ibm.com/support/pages/aix-support-lifecycle-information, the official lifecycle page for this product.
The markdown page for IBM AIX will be created separately.

[AIX] Add IBM AIX version scraper

---

src/common/git.py
src/debian.py
src/red-hat-openshift.py

This adds a script to get release informations for https://endoflife.date/red-hat-openshift
The docs repo is the source for this information:
https://github.com/openshift/openshift-docs
Each major release has a dedicated branch and a release file (for example release_notes/ocp-4-10-release-notes.adoc). A regex expression is used to extract the versions and dates.
The repository is pretty large, so I tried to keep the fetch operations to a minimum.

add red-hat-openshift script

---

src/apache-http-server.py
src/apache.py

This script fetches informations from the https://github.com/apache/httpd repo.
Every branch formated like 2.4.x has a `STATUS` file which contains a version history.
Not every version was released, so I filter the lines with `(?:Released|Announced)` to get the released versions only (they were not rly consistent in the past with the wording, it seems better now).
They use the format `Month Day, Year` and I try to parse the date and convert it to the required format. Dates which fail this process are filtered out.

[apache] add automation script

---

Gemfile.lock

Closes #129: @dependabot does not have the rights to commit to the repository, hence the "update data" workflow fails.

Update ruby dependencies

---

update.rb

Since #137 the Ruby `dockerhub` auto method has been replaced by the Python-based one named `docker_hub`.

Drop Ruby dockerhub auto method code

---

src/aws-lambda.py
src/common/endoflife.py

The purpose of this new script is to be alerted of new runtimes, while not making updates to the original product file (because release dates cannot be fetched from AWS documentation).
Relates to https://github.com/endoflife-date/endoflife.date/pull/3982.

[aws-lambda] Add automation

---

src/common/endoflife.py
src/cos.py
src/firefox.py

Move the parallel URL fetching from `firefox.py` to `endoflife.py` to make available parallel URL fetching for all scripts.
Also implement a fix found on https://stackoverflow.com/a/44511691/374236 to avoid `ChunkedEncodingError`.

Support parallel URL fetching via endoflife.fetch_urls

---

src/common/git.py
src/eks.py
src/firefox.py
src/graalvm.py
src/ros.py

I followed https://adamj.eu/tech/2019/09/12/how-i-import-pythons-datetime-module/ to fix the `datetime` warning.
Is there any interest in adding a linter and/or formatter to the CI?

Fix some lint warnings

---

src/common/endoflife.py
src/unity.py

When a `ChunkedEncodingError` occurs, request and response are not set and there is no way to get the URL that causes the error. With this change all URLs are retried. The `max_retries` parameter is decreased each time so that we do not get stuck in an infinite loop.
I also considered to also wait before retrying, but for now I don't see any benefit to it.
Relates to https://github.com/endoflife-date/release-data/pull/188.

Improve retry mechanism

---

src/coldfusion.py
src/common/dates.py

- Fixes #81
~~The website does not have release dates~~, so this instead fetches the hotfix by making a HEAD request instead to get the last modified date on the hotfix file.  The dates seem reasonable:
```json
{
"10.0.19.298511": "2016-04-20",
"10.0.20.299202": "2016-06-08",
"10.0.21.300068": "2016-08-25",
"10.0.22.301868": "2016-12-20",
"10.0.23.302580": "2017-04-22",
"11.0.01.291346": "2014-09-22",
"11.0.02.291725": "2014-12-02",
"11.0.03.292480": "2014-12-09",
"11.0.04.293328": "2015-02-19",
"2016.0.02.299200": "2016-06-08",
"2016.0.03.300466": "2016-10-07",
"2016.0.04.302561": "2017-04-19",
"2016.0.05.303689": "2017-08-31",
"2016.0.06.308055": "2018-04-09",
"2016.0.07.311392": "2018-09-11",
"2016.0.09.314003": "2019-02-21",
"2016.0.10.314028": "2019-02-27",
"2016.0.11.314546": …
```

[coldfusion] Adds coldfusion release automation

---

src/common/endoflife.py
src/git.py

Note that this also changed the module used for regexes in endoflife.py. The regex module is now used because the Python re module does not support identically named groups (as used in the mariadb product). The regex module being backwards-compatible with the standard re module, this should not be an issue.

[git] Refactor script

---

src/common/endoflife.py

This method is unused now that all scripts are using the Product class.

Remove unused write_releases method

---

latest.py
requirements.txt

It makes more sense as it is closely related to the JSON version file format, which is more subject to change than the product file format.

Migrate latest.py from endoflife.date to release-data

---

requirements.txt

Reverts endoflife-date/release-data#265.
This makes the deployment to Netlify fail (see https://github.com/endoflife-date/endoflife.date/pull/4403).

Revert "Bump pre-commit from 3.5.0 to 3.6.0"

---

latest.py

ruamel is using aliases when the same instance of a date is used at multiple places (such as in https://github.com/endoflife-date/endoflife.date/pull/4368). This overcome this issue by cloning the date object before updating releases.
See also https://stackoverflow.com/a/64717341/374236.

Avoid the use of aliases when dumping product files in latest.py

---

.github/workflows/update.yml

This is good because checking out a non-existing branch:
- takes nearly 30s, and most PR does not have a branch with the same name declared in both release-data and endoflife.date repository,
- pollute workflow summary with cryptic error messages.
So overall this save a lot of time and is cleaner.

Do not checkout the website repository twice in update.yml

---

latest.py

Updates were ignored when versions could not be compared (e.g. if at least one of the version did not conform to PEP 440). This improves the process by comparing by version dates in that case.

Compare by date when version compare is not possible in latest.py

---

src/common/endoflife.py

Support a new regex_exclude option to describe versions that must be excluded from the list of retrieved versions.
This will be useful for products such as KDE Plasma, for which beta releases are designated by the use of minor or patch version >= 80.

Support exclusions in auto configurations

---

src/ibm-aix.py

Disabled because it causes too many timeouts / errors, see https://github.com/endoflife-date/release-data/actions/runs/7630234550 or https://github.com/endoflife-date/release-data/actions/runs/7636410022.

[ibm-aix] Stop fetching version from web.archive.org

---

src/cgit.py
src/common/endoflife.py
src/distrowatch.py
src/docker_hub.py
src/git.py
src/github-releases.py
src/maven.py
src/npm.py
src/pypi.py

Make endoflife.list_products return product instead of just the product name, to avoid having to reload the product a second time to get more information.

Simplify endoflife.list_products usage

---

src/aws-lambda.py
src/common/releasedata.py
src/firefox.py
src/unity.py

Generic support for cumulative updates has been added to speed up execution time of some scripts that were very long (in comparison with the vast majority of products), usually because they were involving a lot of HTTP requests.
This feature was developed particularily for the firefox.py and unity.py scripts, which was often very long to execute (a minute or moreaccording to GHA summaries). Those scripts has been updated to make use of this new feature.

[firefox][unity] Add support for cumulative updates and use it in a few scripts

---

src/common/endoflife.py

Scripts were processed in alphabetic order, but not products inside multi-products scripts.

Process products in alphabetic order for a given method

---

src/apple.py
src/aws-lambda.py
src/cgit.py
src/common/endoflife.py
src/common/gha.py
src/common/releasedata.py
src/distrowatch.py
src/docker_hub.py
src/firefox.py
src/git.py
src/github_releases.py
src/maven.py
src/npm.py
src/palo-alto-networks.py
src/pypi.py
src/unity.py
update.py

Until now products could declare multiple auto-update methods, but they all had to be of the same kind. For example if you used the git auto-update method, you could not use an additional github_releases or custom auto-update method. This is an issue as it prevents us to extend the auto-update process, for example by having a product using the 'git' auto-update method to retrieve all the versions, and a custom script to retrieve support and EOL dates.
This improve the scripts execution orchestration to be able to support auto configurations using a mix of methods, meaning:
- multiple kind of methods, such as git and github_release,
- or multiple custom methods.
A side-effect of those changes is that now a failure in a generic script does not cancel the update of subsequent products. …

Improve scripts execution orchestration

---

releases/akeneo-pim.json
src/common/endoflife.py
src/common/releasedata.py
src/release_table.py

Add a new `release_table` method to automate the retrieval of release-level information such as `releaseDate`, `support` or `eol` fields.

Add the new release_table method

---

latest.py

Such as https://github.com/endoflife-date/endoflife.date/commit/688beefd7ab7e047a2b9ce04b308dfffc916aa00.

Stop wrapping line when updating product data

---

src/release_table.py

Support parsing dates when only the month and the year is provided. Day is always set to the end of the month.

[release_table] Support month_year_date type

---

src/release_table.py

Do not skip the remaining cells/rows of a table when the parsing of a single cell fails.

[release_table] Stop skipping table on cell parsing error

---

src/release_table.py

Partial dates are parsed as month_year dates and set to the end of the month.

[release_table] Make date type accept both full and partial dates

---

src/release_table.py

This new type converts a comma-separated list of values into a range, only keeping the first and last value. For example, `1.0, 1.1, 1.2` becomes `1.0 - 1.2`.

[release_table] Add support for 'range' type

---

src/github_releases.py

It is usually simpler to parse, align with the `git`method, and gives better results by default.

[github_releases] Use tag name instead of release name

---

src/red-hat-openshift.py

The Red Hat people changed the [format of the dates](https://github.com/openshift/openshift-docs/commit/5b65b4de8d6e98f5e4de297300f8c25d597ffbe5) AND the format of the versions from this:
`=== RHSA-2024:5808 - {product-title} 4.12.64 bug fix and security update`
to this
`=== RHSA-2024:0041 - {product-title} {product-version}.0 image release, bug fix, and security update advisory`.
But not for all branches, but only for the latest (4.16 and up).
Fixes #378

Fix openshift pattern

---

update.py

The update.py script logs loaded product data. As they are not contained within a log group, they clutter the GitHub Actions log without really providing any benefit. By moving them into a group, they are hidden by default.

Add log group for loaded product data

---

requirements.txt

Reverts endoflife-date/release-data#386, 0.2.12 not available during Netlify build (https://app.netlify.com/sites/endoflife-date/deploys/67577a6c7a621e0008069da6).

Revert "Bump ruamel-yaml-clib from 0.2.8 to 0.2.12"

---

README.md

Believe it or not, my original intent was just to fix the typo `built`→`build`, but I got carried away :sweat_smile:

Context, wording and punctuation improvements to the README.md

---

src/common/github.py
src/github_tags.py

Add a new method to fetch tags with their related commit date using GitHub GraphQL API.
For large repositories, such as https://github.com/gregkh/linux, it may be more performant than the git auto method.

Add github_tags auto method

---

src/redhat_lifecycles.py

An auto method based on the Red Hat Product Life Cycle Data API (https://access.redhat.com/product-life-cycles/api/v1/products).
Credits for this new method goes to @dfuenzalida :pray:

Add redhat_lifecycles auto method

---

.github/workflows/update.yml
src/apple.py
src/common/http.py

Allow stale responses in case of error in order to reduce the number of temporary errors.
Note that the cache will be reset on the first build of every week in any cases, see .github/workflows/update.yml.

Respect HTTP Cache-Control header if available

---

src/netbsd.py

Empty EOL cells are now recognized as `Â`, adding a condition to ignore them.

[netbsd] Skip invalid EOL date

---

src/common/releasedata.py

Automatically normalize release names. This may be useful in a few situations to avoid having to write a custom script.

Normalize release names

---

src/common/endoflife.py

Include all spaces characters (matching \s in a regex), not just the standard space character.

Improve string to identifier transformation

---

src/libreoffice.py

LibreOffice data may contain prerelease versions. Those should not be included in release data: endoflife.date only list GA releases.
Fixes #511.

[libreoffice] Ignore prereleases
