src/apple.py, src/distrowatch.py, src/eks.py, src/haproxy.py, src/maven.py, src/palo-alto-networks.py, src/pypi.py, src/rhel.py, src/ros.py, src/unrealircd.py
* [apple,haproxy,palo-alto-networks,rhel,ros,unrealircd] Rename variables shadowing built-in names
* [eks,palo-alto-networks] Remove unused variables
* [eks,palo-alto-networks] Rename variables shadowing names from outer scopes
* [maven] use snake_case for variable names
* [apple,distrowatch,pypi] Remove unused imports
=> Cleanup code

src/cos.py
Google Docs website returns a lot of SSL errors, so retry
=> [cos] Retry requests on failure

src/firefox.py
It's pretty basic, but it should work (we should use [one of the solutions in https://copdips.com/2021/01/python-requests-with-retry.html, preferably ](https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/#retry-on-failure).
=> [firefox] Retry on timeout

src/cos.py
There's no need for this to be manually-maintained list, the milestones are listed on the release notes page and aren't too difficult to extract.
=> Automatically find COS milestones in the web page

src/artifactory.py
Releases were deleted a few times (see #124), hopefully this will make things better.
=> [artifactory] Increase sleep timeout and scrolldown count

src/apple.py
Fixes a small issue with missing tables
=> [apple] Fix slight html change

docker_hub.py
Will replace Ruby-implemented dockerhub method (only used by Amazon Linux at the moment.
=> Add docker_hub method

src/common/endoflife.py
Intermittent ChunkedEncodingErrors occurs while fetching URLs. This change try to fix it by retrying.
According to https://stackoverflow.com/a/44511691/374236, most servers transmit all data, but that's not what was observed.
For future reference the traceback was:
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/runner/work/release-data/release-data/src/firefox.py", line 36, in <module>
for response in endoflife.fetch_urls(urls):
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/work/release-data/release-data/src/common/endoflife.py", line 55, in fetch_urls
return [future.result() for future in as_completed(futures)]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Try to fix fetch_urls when ChunkedEncodingError occurs

src/cos.py
Its cuts the script execution time roughly by two during my tests.
=> [cos] Make HTTP requests in parallel

src/haproxy.py
Its cuts the script execution time roughly by three during my tests.
=> [haproxy] Make HTTP requests in parallel

src/couchbase-server.py
Its cuts the script execution time roughly by two during my tests.
=> [couchbase] Make HTTP requests in parallel

src/splunk.py
Its cuts the script execution time roughly by three during my tests.
=> [splunk] Make HTTP requests in parallel

src/common/endoflife.py, src/common/git.py, src/common/http.py
Add some basic logging when using common.git or common.http.
=> Add some basic logging

src/common/dates.py
This will be useful in future PRs:
- add a few more supported formats,
- cleanup string so that we don't have to deal with some special characters in formats.
=> Improve date support

src/common/endoflife.py
This will be used in future PR to simplify existing script and lay fundation for tracking more than versions.
=> Add endoflife.Product class

src/amazon-neptune.py
Make the script more readable, partly by making use of the new `endoflife.Product` class.
=> [amazon-neptune] Refactor script

src/amazon-neptune.py, src/apache-http-server.py
- removing the unnecessary use of functions,
=> [apache-http-server] Refactor script

src/apple.py, src/common/dates.py, src/common/endoflife.py
- removing the unnecessary use of functions,
=> [apple] Refactor script

src/apple.py, src/artifactory.py, src/common/dates.py, src/common/endoflife.py
- removing the unnecessary use of functions,
=> [artifactory] Refactor script

src/aws-lambda.py
=> [aws-lambda] Refactor script

src/cgit.py, src/common/endoflife.py
- introducing the endoflife.AutoConfig class to make it easier to manage such configurations,
- removing the unnecessary use of functions,
=> [cgit] Refactor script

src/coldfusion.py
- removing some unnecessary use of functions,
=> [coldfusion] Refactor script

src/confluence.py
=> [confluence] Refactor script

src/cos.py
=> [cos] Refactor script

src/couchbase-server.py
=> [couchbase-server] Refactor script

src/debian.py
=> [debian] Refactor script

src/common/endoflife.py, src/distrowatch.py
=> [distrowatch] Refactor script

src/docker_hub.py
=> [docker_hub] Refactor script

src/firefox.py
=> [firefox] Refactor script

src/common/endoflife.py, src/git.py, src/github-releases.py
The script also now correctly handles the `template` parameter in auto configs.
=> [github_releases] Refactor script

src/gke.py
=> [gke] Refactor script

src/graalvm.py
=> [graalvm] Refactor script

src/haproxy.py
=> [haproxy] Refactor script

src/confluence.py, src/jira.py
=> [jira] Refactor script

src/looker.py
=> [looker] Refactor script

src/maven.py
This auto method also now support custom regexes and template.
=> [maven] Refactor script

src/nutanix.py
=> [nutanix] Refactor script

src/oracle-jdk.py
=> [oracle-jdk] Refactor script

src/palo-alto-networks.py
=> [palo-alto-network] Refactor script

src/pypi.py
This script also now support custom template.
=> [pypi] Refactor script

src/plesk.py
=> [plesk] Refactor script

src/red-hat-openshift.py
- a little bit of renaming and documentation,
- removing the use of functions when unnecessary.
=> [red-hat-openshift] Refactor script

src/rds.py
=> [rds] Refactor script

src/redhat-satellite.py
=> [redhat-satellite] Refactor script

src/rhel.py
=> [rhel] Refactor script

src/rockylinux.py
- a little bit of renaming and documentation,
- removing the use of functions when unnecessary.
=> [rockylinux] Refactor script

src/sles.py
=> [sles] Refactor script

src/ros.py
=> [ros] Refactor script

src/splunk.py
=> [splunk] Refactor script

src/typo3.py
=> [typo3] Refactor script

src/unity.py
=> [unity] Refactor script

src/unrealircd.py
=> [unrealircd] Refactor script

.github/workflows/update.yml, latest.py, src/common/gha.py, update.py
- create new gha.py module,
- improve GitHub workflow commands (`GITHUB_OUTPUT`, `GITHUB_STEP_SUMMARY`) interactions,
- improve logging,
- split update.py into smaller functions.
=> Refactor latest.py and update.py

src/common/endoflife.py
Small refactoring to simplify product listing by reusing ProductFrontmatter.
=> Simplify product listing

latest.py
This was previously possible using https://github.com/endoflife-date/endoflife.date/blob/68bfaa0023d1f6e809506730d30ba8667a75d304/_auto/bulk-update.py. This change removes the need of such script, while reusing existing code to perform the upgrade.
=> Support product bulk-upgrade in latest.py

src/aws-lambda.py
There is a mistake in the data: block function update date cannot be before the deprecation date.
=> [aws-lambda] Fix nodejs4.3-edge block function update date

latest.py
Long list of deprecated releases are listed in auto-update endoflife.date PRs such as https://github.com/endoflife-date/endoflife.date/pull/4612#issuecomment-1945987036.
This only shows releases that are still active in the past 30 days.
=> Suppress alerts for outdated unmatched releases

src/common/releasedata.py
This is better than just checking if both the releases and versions list are empty.
=> Raise error when a script did not perform any update in a product

src/release_table.py
It has been observed that in many cases, such as for amazon-neptune or amazon-corretto, data is split in two tables: supported and unsupported. Those table usually have similar column names, so by allowing mutiple tables the configuration is simplified.
Also fix script's documentation and improve logging.
=> [release-table] Support parsing multiple tables

src/release_table.py
- Change `headers_selector` to `header_selector`: there was no need to ask the header cell selection, so updated it to match rows selection.
- Set `header_selector` default value to `thead tr`.
- Set `rows_selector`  default value to `tbody tr`.
=> [release_table] Simplify header and row selection

src/common/http.py, src/release_table.py
This allows more elements to be rendered before parsing the page.
=> [release_table] Allow clicking on page after the JavaScript rendering

requirements.txt
This reverts commit d0f5f98dd9af617c2748eeca7a6d77ec9a137fae.
=> Revert "Bump pre-commit from 3.5.0 to 3.7.0 (#336)"

src/common/dates.py, src/libreoffice.py
Based on https://downloadarchive.documentfoundation.org/libreoffice/old/
=> [libreoffice] Adds automation

src/common/endoflife.py
Such errors prevent the script to run.
=> Do not fail in update.py if a product cannot be loaded

src/chef-infra-client.py
Relates to https://github.com/endoflife-date/endoflife.date/pull/4388.
=> [chef-infra-client] Add automation script

src/kuma.py
Requested in https://github.com/endoflife-date/endoflife.date/pull/5518/files#r1694245645
=> [kuma] adds automation

src/netbsd.py
=> [netbsd] Add automation

src/chef-infra-client.py
Release note page and git repository where those of chef-infra-server.
=> [chef-infra-client] Fix script

src/chef-inspec.py
Similar to chef-infra-client and chef-infra-server.
=> [chef-inspec] Add automation

src/chef-inspec.py, src/common/github.py, src/github_releases.py
GitHub releases give better dates than git tags.
=> [chef-inspec] Use GitHub releases instead of git tags

src/lua.py
Using https://www.lua.org/versions.html.
=> [lua] Automate release and version retrieval

src/splunk.py
There is now a DataMonitoringAppPreview option in the list.
=> [splunk] Filter versions list

releases/motorola-mobility.json, src/common/endoflife.py, src/motorola-security.py
Based on https://gist.github.com/ab/67c6343530c6b8e599f07cedccbcba3d.
Closes #277.
=> [motorola-security] Add auto method

src/virtualbox-releases.py, src/virtualbox-versions.py, src/virtualbox.py
Track versions using the download URL.
Corresponding product PR: https://github.com/endoflife-date/endoflife.date/pull/7950
=> [virtualbox] Add support for versions

update-product-data.py
So that it can be directly copy-pasted to endoflife.date sources.
=> [update-product-data] Print unmatch release as YAML

update-product-data.py
Improve YAML list indentation to be aligned with what is done by IDE or by linters such as Prettier.
=> [update-product-data] Improve YAML list indendation

releases/debian.json, releases/statamic.json, src/_remove_invalid_releases.py, src/common/releasedata.py, src/release_table.py
remove_if_undefined allows to exclude unreleased release more easily.
=> [release_table] Add remove_if_undefined parameter

src/freebsd-releases.py
=> [freebsd-releases] Add auto method
